### ISSUE TITLE
smtpuser

### ISSUE THREAD

**Issue by solidstatefarms** [gitbls/pistrong#9]
Hi. I'm trying to configure pistrong with an external smtp server, but it appears that maybe the smtp user configuration value is not fully implemented? This is the error message I'm getting. I looked briefly at the code as well and there are only a couple references to the smtpuser parameter. 

pi@swan:/etc/swanctl/pistrong $ sudo pistrong config --smtpuser user@domain.com
usage: pistrong [-h]
                {config,createca,deleteca,showcert,makevpncert,makecacert,showca,listca,add,delete,revoke,list,resend,service,client,help,version}
                ...
pistrong: error: unrecognized arguments: --smtpuser user@domain.com
pi@swan:/etc/swanctl/pistrong $

**Comment by gitbls** [comment]
Thanks for giving pistrong a go. Indeed, while the smtpuser configuration item is present in the database, there's currently no way to change it with the `pistrong config` command. 

There are two ways you could consider addressing this: 

- You CAN edit the database (/etc/swanctl/pistrong/pistrongdb.json) to set it, in order for you to continue your testing/implementation, although I can't guarantee that pistrong will be able to send mail properly to an external mail server, since there are so many variations and complications.
- You could set up a mail server on your LAN that forwards email to an internet-based mail server. This is really straightforward. You could use a simple smtp forwarder such as msmtp, or a full-fledged mail server such as postfix. I use postfix, and have found it to be relatively lightweight, easy to configure in this mode, and quite reliable.

If you opt to go with the LAN mail server approach, I can provide you with some guidance/scripts to simplify the process.

I'd like to complete the smtp configuration in pistrong, but won't be able to get to it for a while.

Let me know your thoughts on this. Happy to help you progress with one of the above approaches.

**Comment by solidstatefarms** [comment]
Thanks for the advice. For the time being I am creating the user and then manually copying the zip file to the web directory, from which I can then grab it remotely on the client machine. I am in testing mode but when I get it working and am ready to deploy it to my clients, I will try the two methods you describe. I never realized that it was simple to set up a local mail relay that could send to an internet mail server. I will give that a try when I have a chance, since I have another project in development that could use this functionality.

**Comment by gitbls** [comment]
I'm working on pistrong again, and have implemented smtpuser, as well as documentation and testing for sending using gmail and outlook.com. Still have some testing to do on this and a few other areas, but should have this completed late this week or early next week. Cheers.

**Comment by gitbls** [comment]
Updates checked in to correct smtpuser and enable sending mail using gmail or outlook.com. I'll leave this open for a week or to so you can test/verify.

**Comment by solidstatefarms** [comment]
thanks, I will test this next week.

**Comment by gitbls** [comment]
Since I've verified that it's fixed and you have not responded, I'm going to close this. If you have further issues with this topic, please feel free to reopen it, or start a new issue. Thanks!
